export const data = [
  {
    id: 1,
    name: "iPhone 8",
    image: "../../assets/iPhone-8.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 300,
    category: "A",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 2,
    name: "iPhone 10",
    image: "../../assets/iPhone-X.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "B",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 3,
    name: "iPhone 11",
    image: "../../assets/iPhone-11.png",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 600,
    category: "A",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 4,
    name: "iPhone 12",
    image: "../../assets/iPhone-12.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 800,
    category: "B",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 5,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 6,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 7,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 8,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 9,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 10,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 11,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 12,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 13,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 14,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
  {
    id: 15,
    name: "iPhone SE",
    image: "../../assets/iPhone-se.jpg",
    desc:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto fugit dolorem dignissimos earum assumenda. ",
    price: 400,
    category: "C",
    availability: "InStock",
    inCart: false,
    amount: 0,
    total: 0,
  },
];
